### ISSUE TITLE
Pull access denied ?

### ISSUE THREAD

**Issue by wkulesza** [IsraelHikingMap/graphhopper-docker-image-push#4]
Hi,
I'm trying to run
```
docker run --entrypoint /bin/bash israelhikingmap/graphhhopper -c "wget https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf -O /data/berlin.osm.bpf && java -Ddw.graphhopper.datareader.file=/data/berlin.osm.pbf -Ddw.graphhopper.graph.location=berlin-gh -jar *.jar server config-example.yml"
```
and i receive:
```
Unable to find image 'israelhikingmap/graphhhopper:latest' locally

docker: Error response from daemon: pull access denied for israelhikingmap/graphhhopper, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Please help.

edit1:
I pull the image first manually, then when started, it saved the berlin file, but after start of server it can't find it:
```
2021-09-09 08:37:45.358 [main] INFO  o.e.jetty.setuid.SetUIDListener - Opened application@73ad7e90{HTTP/1.1, (http/1.1)}{localhost:8989}
2021-09-09 08:37:45.360 [main] INFO  o.e.jetty.setuid.SetUIDListener - Opened admin@4ba380c7{HTTP/1.1, (http/1.1)}{localhost:8990}
2021-09-09 08:37:45.363 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.4.39.v20210325; built: 2021-03-25T14:42:11.471Z; git: 9fc7ca5a922f2a37b84ec9dbc26a5168cee7e667; jvm 11.0.12+7
2021-09-09 08:37:45.396 [main] INFO  com.graphhopper.GraphHopper - version 4.0|2021-09-09T01:56:19Z (5,19,4,4,5,7)
2021-09-09 08:37:45.403 [main] INFO  com.graphhopper.GraphHopper - graph CH|car|RAM_STORE|2D|no_turn_cost|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308, CHGraph|car|NODE_BASED, shortcuts:0 (0MB), nodesCH:0 (0MB)
2021-09-09 08:37:45.665 [main] INFO  com.graphhopper.GraphHopper - No custom areas are used, custom_areas.directory not given
2021-09-09 08:37:45.685 [main] INFO  com.graphhopper.GraphHopper - start creating graph from /data/berlin.osm.pbf
2021-09-09 08:37:45.702 [main] INFO  com.graphhopper.GraphHopper - using CH|car|RAM_STORE|2D|no_turn_cost|,,,,, memory:totalMB:186, usedMB:18
2021-09-09 08:37:45.706 [main] ERROR io.dropwizard.cli.ServerCommand - Unable to start server, shutting down
java.lang.IllegalStateException: Your specified OSM file does not exist:/data/berlin.osm.pbf
        at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:146)
        at com.graphhopper.GraphHopper.importOSM(GraphHopper.java:708)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:672)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:635)
        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:103)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:423)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:387)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:60)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:35)
java.lang.IllegalStateException: Your specified OSM file does not exist:/data/berlin.osm.pbf
        at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:146)
        at com.graphhopper.GraphHopper.importOSM(GraphHopper.java:708)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:672)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:635)
        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:103)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:423)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:387)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:60)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at com.graphhopper.http.GraphHopperApplication.main(GraphHopperApplication.java:35)
```

**Comment by HarelM** [comment]
I'm not sure I fully understand what you did.
Can you please specify the exact steps you did and what did you expect to happen?
Keep in mind that we use a docker volume to store the graphhopper data so that it won't be deleted between activations of the image.
If the instructions are not clear enough we would be happy to get a PR with a more elaborated readme file for other to use.
We are using this docker image for a while now without any issues...
Also I would recommend using a released version and not the latest if you don't need to test features that just came out and might not be stable...

**Comment by wkulesza** [comment]
Hi @HarelM thankx for getting back so quickly.
I'm trying to run a docker image with graphhopper with osm data from Poland, so trying first with default berlin configuration.
So i first did:
docker pull israelhikingmap/graphhopper
and then:
docker run --entrypoint /bin/bash israelhikingmap/graphhopper -c "wget https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf -O /data/berlin.osm.bpf && java -Ddw.graphhopper.datareader.file=/data/berlin.osm.pbf -Ddw.graphhopper.graph.location=berlin-gh -jar *.jar server config-example.yml"

BTW, in the readme, you have a syntax - israelhikingmap/graphhhopper  - three "h" instead of two.

**Comment by zstadler** [comment]
When executing `docker run` a new container is created from the image. This container is deleted once the task has completed.
If the ``/data` is not bound to a directory on the host machine, its contents will be lost once `wget` has finished the download and the container is removed.

I suggest reading more about the way docker works: the difference between images and containers, volumes and binding, `docker run` vs. `docker run --detach` vs. `docker exec`, etc.

**Comment by HarelM** [comment]
Also the latest version doesn't have graphhopper.sh file since it was removed by GH team. Please use version 3...

**Comment by HarelM** [comment]
No response from the issue's author.
Closing...
