### ISSUE TITLE
Docker container doesnt start

### ISSUE THREAD

**Issue by iboates** [IsraelHikingMap/graphhopper-docker-image-push#42]
I just tried to run the docker container from scratch but I get an error. I just copied the example right from the readme, am I missing something?

```
me@mycomputer:~/code/graphhopper-play$ docker run -p 8989:8989 israelhikingmap/graphhopper --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf --host 0.0.0.0
## using java 21.0.1 (64bit) from /opt/java/openjdk
  HTTP/1.1 200 OK
  Content-Length: 3099644
  Content-Type: application/octet-stream
  Date: Thu, 19 Dec 2024 12:47:58 GMT
  Server: Apache
  Last-Modified: Thu, 19 Dec 2024 01:43:05 GMT
  ETag: "2f4bfc-62995a6c41c40"
  Accept-Ranges: bytes
  Age: 0
  X-Cache: HIT from download-proxy8
  X-Cache-Lookup: HIT from download-proxy8:80
  Via: 1.1 download-proxy8 (squid/5.6)
  Connection: keep-alive
2024-12-19 12:47:59 URL:https://download.geofabrik.de/europe/andorra-latest.osm.pbf [3099644/3099644] -> "data.pbf" [1]
## Executing server. JAVA_OPTS=-Xmx1g -Xms1g
2024-12-19 12:48:00.429 [main] INFO  i.d.core.server.DefaultServerFactory - Registering jersey handler with root path prefix: /
2024-12-19 12:48:00.431 [main] INFO  i.d.core.server.DefaultServerFactory - Registering admin handler with root path prefix: /
2024-12-19 12:48:00.577 [main] INFO  io.dropwizard.assets.AssetsBundle - Registering AssetBundle with name: assets for path /maps/*
2024-12-19 12:48:00.578 [main] INFO  io.dropwizard.assets.AssetsBundle - Registering AssetBundle with name: webjars for path /webjars/*
2024-12-19 12:48:00.583 [main] INFO  i.d.core.server.ServerFactory - Starting GraphHopperApplication
                        _     _
   __ _ _ __ __ _ _ __ | |__ | |__   ___  _ __  _ __   ___ _ __
  / _` | '__/ _` | '_ \| '_ \| '_ \ / _ \| '_ \| '_ \ / _ \ '__|
 | (_| | | | (_| | |_) | | | | | | | (_) | |_) | |_) |  __/ |
  \__, |_|  \__,_| .__/|_| |_|_| |_|\___/| .__/| .__/ \___|_|
  |___/          |_|                     |_|   |_|
2024-12-19 12:48:00.651 [main] INFO  o.e.jetty.setuid.SetUIDListener - Opened application@7e1f584d{HTTP/1.1, (http/1.1)}{0.0.0.0:8989}
2024-12-19 12:48:00.652 [main] INFO  o.e.jetty.setuid.SetUIDListener - Opened admin@7dff6d05{HTTP/1.1, (http/1.1)}{0.0.0.0:8990}
2024-12-19 12:48:00.654 [main] INFO  org.eclipse.jetty.server.Server - jetty-10.0.23; built: 2024-08-14T01:14:42.815Z; git: 570aa4a1395ca8f9f800045f3a1fe5fe3af9a598; jvm 21.0.1+12-LTS
2024-12-19 12:48:00.668 [main] INFO  com.graphhopper.GraphHopper - version 11.0|2024-12-19T02:36:58Z (9,23,7,5,2,9)
2024-12-19 12:48:00.690 [main] ERROR i.dropwizard.core.cli.ServerCommand - Unable to start server, shutting down
java.lang.IllegalArgumentException: Encoded values missing: road_access.
To avoid that certain encoded values are automatically removed when you change the custom model later, you need to set the encoded values manually:
graph.encoded_values: car_access, car_average_speed, road_access
        at com.graphhopper.GraphHopper.prepareImport(GraphHopper.java:852)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:799)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:774)
        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:44)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
        at org.eclipse.jetty.server.Server.start(Server.java:470)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
        at org.eclipse.jetty.server.Server.doStart(Server.java:415)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at io.dropwizard.core.cli.ServerCommand.run(ServerCommand.java:52)
        at io.dropwizard.core.cli.EnvironmentCommand.run(EnvironmentCommand.java:67)
        at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
        at io.dropwizard.core.cli.Cli.run(Cli.java:78)
        at io.dropwizard.core.Application.run(Application.java:94)
        at com.graphhopper.application.GraphHopperApplication.main(GraphHopperApplication.java:38)
2024-12-19 12:48:00.692 [main] INFO  org.eclipse.jetty.server.Server - Stopped Server@6642dc5a{STOPPING}[10.0.23,sto=30000]
2024-12-19 12:48:00.692 [main] INFO  org.eclipse.jetty.server.Server - Shutdown Server@6642dc5a{STOPPING}[10.0.23,sto=30000]
2024-12-19 12:48:00.695 [main] WARN  i.dropwizard.core.cli.ServerCommand - Failure during stop server
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: STOPPED
        at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
        at org.eclipse.jetty.server.Server.doStop(Server.java:490)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at io.dropwizard.core.cli.ServerCommand.run(ServerCommand.java:56)
        at io.dropwizard.core.cli.EnvironmentCommand.run(EnvironmentCommand.java:67)
        at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
        at io.dropwizard.core.cli.Cli.run(Cli.java:78)
        at io.dropwizard.core.Application.run(Application.java:94)
        at com.graphhopper.application.GraphHopperApplication.main(GraphHopperApplication.java:38)
Caused by: java.lang.IllegalStateException: STOPPED
        at org.eclipse.jetty.server.handler.ContextHandler.shutdown(ContextHandler.java:773)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at org.eclipse.jetty.util.component.Graceful.shutdown(Graceful.java:146)
        ... 8 common frames omitted
java.lang.IllegalArgumentException: Encoded values missing: road_access.
To avoid that certain encoded values are automatically removed when you change the custom model later, you need to set the encoded values manually:
graph.encoded_values: car_access, car_average_speed, road_access
        at com.graphhopper.GraphHopper.prepareImport(GraphHopper.java:852)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:799)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:774)
        at com.graphhopper.http.GraphHopperManaged.start(GraphHopperManaged.java:44)
        at io.dropwizard.lifecycle.JettyManaged.doStart(JettyManaged.java:27)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
        at org.eclipse.jetty.server.Server.start(Server.java:470)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
        at org.eclipse.jetty.server.Server.doStart(Server.java:415)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at io.dropwizard.core.cli.ServerCommand.run(ServerCommand.java:52)
        at io.dropwizard.core.cli.EnvironmentCommand.run(EnvironmentCommand.java:67)
        at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
        at io.dropwizard.core.cli.Cli.run(Cli.java:78)
        at io.dropwizard.core.Application.run(Application.java:94)
        at com.graphhopper.application.GraphHopperApplication.main(GraphHopperApplication.java:38)
```

**Comment by HarelM** [comment]
The docs in graphhopper repo is using version 10 and not latest main branch, I believe we should follow their instructions.
Use the following command:
`docker run -p 8989:8989 israelhikingmap/graphhopper:10.0 --url https://download.geofabrik.de/europe/andorra-latest.osm.pbf --host 0.0.0.0`
